name: "Run build"
description: "Build the application"

inputs:
  npm-token:
    description: "NPM token for private packages"
    required: true

runs:
  using: "composite"
  steps:
    - uses: runs-on/action@v2

    - name: Install dependencies
      uses: ./.github/workflows/composites/install-dependencies
      with:
        npm-token: ${{ inputs.npm-token }}

    - name: Run build
      run: npm run build
      shell: bash
