"use client";

import type { Site } from "@watchborne/charge-points-types";
import { Button } from "@watchborne/electrons";
import { FileDown, Loader2 } from "lucide-react";
import { useLocale, useTranslations } from "next-intl";
import { useState } from "react";

import { isLocale } from "@/i18n/locale";
import { api } from "@/lib/api";

type Props = {
  site: Site;
};

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};

/**
 * Used only if the server sent no `Content-Disposition` filename: the same
 * ASCII slug the backend would have made (`Site Nord — Été` → `site-nord-ete`).
 */
const fallbackFilename = (site: Site) => {
  const slug = site.name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();

  return `${slug || "site"}-report.pdf`;
};

/**
 * Downloads the site's printable report (issue charge-points-server#532) as a
 * PDF. The report is generated by the backend (charge-points-server ADR 0023):
 * it reads its own data, draws its own charts and writes the file in the
 * dashboard's language, so all this does is ask for it and hand the file to the
 * browser.
 */
export const SiteReportExportButton = ({ site }: Props) => {
  const t = useTranslations("");
  const locale = useLocale();
  const [exporting, setExporting] = useState(false);
  const [exportFailed, setExportFailed] = useState(false);

  const handleExport = async () => {
    setExportFailed(false);
    setExporting(true);
    try {
      const { blob, filename } = await api.Sites.downloadReport(site.id, {
        // The dashboard is only ever served in a supported locale; the guard
        // narrows the type rather than guarding a case that can occur.
        locale: isLocale(locale) ? locale : "fr",
      });
      downloadBlob(blob, filename ?? fallbackFilename(site));
    } catch {
      // `withErrorLogging` has already reported it; the user needs to know to retry.
      setExportFailed(true);
    } finally {
      setExporting(false);
    }
  };

  return (
    <>
      <Button variant="outline" onClick={handleExport} disabled={exporting}>
        {exporting ? (
          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
        ) : (
          <FileDown className="h-4 w-4 mr-2" />
        )}
        {t("appPage.sites.detail.report.exportButton")}
      </Button>

      {exportFailed && (
        <p className="text-xs text-destructive">{t("appPage.sites.detail.report.exportError")}</p>
      )}
    </>
  );
};
