import { Site, SiteWithChargePoints } from "@watchborne/charge-points-types";

import { withErrorLogging } from "./api-error-wrapper";
import { type DownloadedFile, httpClient } from "./http-client";

// `lastVisitedAt` is excluded: the backend derives it from the `SiteVisit`
// history and silently ignores it on POST/PATCH (charge-points-server
// ADR 0015) — log a visit via `api.SiteVisits.record` instead.
type CreateSiteBody = Omit<
  Site,
  "id" | "customerId" | "createdAt" | "updatedAt" | "deletedAt" | "lastVisitedAt"
> & {
  customerId?: Site["customerId"];
};

export type SiteReportQuery = {
  /** The language the report is written in. */
  locale: "fr" | "en";
  /** The report's window; omitted, the backend uses the last seven days ending now. */
  from?: Date;
  to?: Date;
};

type PatchSiteBody = {
  id: string;
} & Partial<CreateSiteBody>;

export const siteApis = {
  getSites: async function (): Promise<SiteWithChargePoints[]> {
    return withErrorLogging(
      () => httpClient.get<SiteWithChargePoints[]>("/api/sites"),
      "Sites.getSites",
    );
  },
  getSite: async function (siteId: Site["id"]): Promise<SiteWithChargePoints | undefined> {
    return withErrorLogging(
      () => httpClient.get<SiteWithChargePoints | undefined>(`/api/sites/${siteId}`),
      `Sites.getSite(${siteId})`,
    );
  },
  createSite: async function (body: CreateSiteBody): Promise<Site> {
    return withErrorLogging(() => httpClient.post<Site>("/api/sites", body), "Sites.createSite");
  },
  updateSite: async function (siteId: Site["id"], patchBody: PatchSiteBody): Promise<Site> {
    return withErrorLogging(
      () => httpClient.patch<Site>(`/api/sites/${siteId}`, patchBody),
      `Sites.updateSite(${siteId})`,
    );
  },
  /**
   * The site's printable report as a PDF, generated by the backend
   * (`GET /api/sites/:id/report.pdf`, charge-points-server ADR 0023): its data
   * is read once server-side and its charts are drawn as vectors, so there is
   * nothing left for the browser to assemble — only a file to hand to the user.
   */
  downloadReport: async function (
    siteId: Site["id"],
    { locale, from, to }: SiteReportQuery,
  ): Promise<DownloadedFile> {
    const params = new URLSearchParams({ locale });
    if (from) params.set("from", from.toISOString());
    if (to) params.set("to", to.toISOString());

    return withErrorLogging(
      () => httpClient.getFile(`/api/sites/${siteId}/report?${params.toString()}`),
      `Sites.downloadReport(${siteId})`,
    );
  },
  deleteSite: async function (siteId: Site["id"]): Promise<void> {
    return withErrorLogging(
      () => httpClient.delete(`/api/sites/${siteId}`),
      `Sites.deleteSite(${siteId})`,
    );
  },
};
