name: "Run typecheck"
description: "Run TS type checker"

inputs:
  npm-token:
    description: "NPM token for private packages"
    required: true

runs:
  using: "composite"
  steps:
    - uses: runs-on/action@v2

    - uses: actions/setup-node@v6
      with:
        node-version-file: "package.json"

    - name: Install dependencies
      uses: ./.github/workflows/composites/install-dependencies
      with:
        NPM_TOKEN: ${{ inputs.npm-token }}

    - name: Run typecheck
      run: npm run typecheck
      shell: bash
