name: "Run lint and format"
description: "Run eslint and prettier"

inputs:
  npm-token:
    description: "NPM token for private packages"
    required: true

runs:
  using: "composite"
  steps:
    - uses: runs-on/action@v2

    - uses: actions/setup-node@v6
      with:
        node-version-file: "package.json"
        cache: "npm"
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      uses: ./.github/workflows/composites/install-dependencies
      with:
        npm-token: ${{ inputs.npm-token }}

    - name: Get Node version
      id: node-version
      uses: ./.github/workflows/composites/get-node-version

    - name: Run lint
      run: npm run lint
      shell: bash

    - name: Check formatting
      run: npm run format:check
      shell: bash
