name: "Run unit tests"
description: "Run unit tests"

inputs:
  npm-token:
    description: "NPM token for private packages"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token for reporting test results on PR"
    required: true

runs:
  using: "composite"
  steps:
    - uses: runs-on/action@v2

    - uses: actions/setup-node@v6
      with:
        node-version-file: "package.json"

    - name: Install dependencies
      uses: ./.github/workflows/composites/install-dependencies
      with:
        npm-token: ${{ inputs.npm-token }}

    - name: Get Node version
      id: node-version
      uses: ./.github/workflows/composites/get-node-version

    - name: Run tests
      run: npm run test:ci
      shell: bash

    - name: Generate test report
      uses: dorny/test-reporter@v1
      with:
        name: "Unit tests"
        path: "junit-reports/*.xml"
        reporter: jest-junit
        list-suites: "failed"
        list-tests: "failed"

    - name: Report results on PR
      uses: ollieb89/test-results-reporter@v1.1.0
      with:
        test-results: "junit-reports/*.xml"
        token: ${{ inputs.GITHUB_TOKEN }}
