name: Deploy Production to Netlify

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-production:
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - name: Run build
        uses: ./.github/workflows/composites/run-build
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Deploy to Netlify (production)
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
